ci : 서버 배포 후 eureka에 등록되었는지 확인

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,8 +63,26 @@ jobs:
               docker stop member-api-instance-1 || true
               docker rm -f member-api-instance-1 || true
             fi
-              docker run --name member-api-instance-1 --network nhn-book-store-network -p 8082:8082 -e SPRING_PROFILES_ACTIVE=instance1 -d lushlife99/nhn-member:${{ github.sha }}
-            
+            docker run --name member-api-instance-1 --network nhn-book-store-network -p 8082:8082 -e SPRING_PROFILES_ACTIVE=instance1 -d lushlife99/nhn-member:${{ github.sha }}
+
+      - name: Check First Instance via Eureka
+        run: |
+          START_TIME=$(date +%s)
+          while : ; do
+            RESPONSE=$(curl -s http://nhn24.store/eureka/eureka/instances/MEMBER-API-1)
+            echo "$RESPONSE" | grep -q '"status":"UP"'
+            if [ $? -eq 0 ]; then
+              echo "First instance is healthy and UP."
+              break
+            fi
+            CURRENT_TIME=$(date +%s)
+            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+            if [ $ELAPSED_TIME -ge 180 ]; then
+              echo "First instance is not healthy within 3 minutes. Aborting deployment."
+              exit 1
+            fi
+            sleep 10
+          done
 
       - name: Deploy to Second Instance
         uses: appleboy/ssh-action@master
@@ -74,8 +92,28 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
+            docker pull lushlife99/nhn-member:${{ github.sha }}
             if [ "$(docker ps -aq --filter "name=member-api-instance-2")" ]; then
               docker stop member-api-instance-2 || true
               docker rm -f member-api-instance-2 || true
             fi
-              docker run --name member-api-instance-2 --network nhn-book-store-network -p 8083:8083 -e SPRING_PROFILES_ACTIVE=instance2 -d lushlife99/nhn-member:${{ github.sha }}
+            docker run --name member-api-instance-2 --network nhn-book-store-network -p 8083:8083 -e SPRING_PROFILES_ACTIVE=instance2 -d lushlife99/nhn-member:${{ github.sha }}
+
+      - name: Check Second Instance via Eureka
+        run: |
+          START_TIME=$(date +%s)
+          while : ; do
+            RESPONSE=$(curl -s http://nhn24.store/eureka/eureka/instances/MEMBER-API-2)
+            echo "$RESPONSE" | grep -q '"status":"UP"'
+            if [ $? -eq 0 ]; then
+              echo "Second instance is healthy and UP."
+              break
+            fi
+            CURRENT_TIME=$(date +%s)
+            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
+            if [ $ELAPSED_TIME -ge 180 ]; then
+              echo "Second instance is not healthy within 3 minutes. Aborting deployment."
+              exit 1
+            fi
+            sleep 10
+          done
